apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-dind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
      - name: docker
        image: docker:20.10.7-dind
        securityContext:
          privileged: true  # Required to run Docker daemon
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""  # Disable TLS to simplify
        volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
      volumes:
      - name: docker-graph-storage
        emptyDir: {}
