# This is a basic workflow to help you get started with Actions

name: LLVM-CICD-DOCKER

# Controls when the workflow will run 
on:
  push:  
    branches: [ "main" ]     
  pull_request:
    branches: [ "main" ]    
  workflow_dispatch:

jobs:
  LLVM_build:
    permissions:
      contents: write
    strategy:
      matrix:
        arch: [arm64]
    runs-on: ${{ matrix.arch == 'arc-runner-set-ampere-llvm-docker' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64  # Specify platforms for multi-arch image
          push: true  # Pushes image to registry
          tags: tinguyen2024/llvm:latest

      - name: Verify image on GitHub (optional)
        run: docker run --rm tinguyen2024/llvm:latest clang --version
