# This is a basic workflow to help you get started with Actions

name: LLVM-CICD

# Controls when the workflow will run 
on:
  push:  
    branches: [ "main" ]     
  pull_request:
    branches: [ "main" ]    
  workflow_dispatch:

jobs:
  LLVM_build:
    permissions:
      contents: write
    strategy:
      matrix:
        arch: [arm64]
    runs-on: ${{ matrix.arch == 'x86' && 'arc-runner-set-x86' || 'arc-runner-set-ampere' }}

    steps:
      - name: Log Operating System Details
        run: |
          echo "Architecture: ${{ matrix.arch }}"
          uname -a
          sudo apt update
          sudo apt install net-tools
          ifconfig
          curl https://github.com/ampere-solution/llvm-project.git  
          lsb_release -a || cat /etc/os-release
          lscpu
          
      - name: Checkout LLVM source code
        uses: actions/checkout@v4
        with:
          repository: llvm/llvm-project
          path: llvm-project

      #- name: Set up build environment
      #  run: |
      #    sudo apt-get update
      #    sudo apt-get install -y build-essential cmake ninja-build python3

      #- name: Configure LLVM build
      #  run: |
      #    mkdir -p llvm-project/build
      #    cd llvm-project/build
      #    cmake -G Ninja \
      #      -DLLVM_ENABLE_PROJECTS="clang" \
      #       -DLLVM_ENABLE_RUNTIMES="libunwind;libcxx;libcxxabi" \
      #      -DLLVM_TARGETS_TO_BUILD="AArch64;X86" \
      #      -DCMAKE_BUILD_TYPE=Release \
      #      -DLLVM_ENABLE_ASSERTIONS=ON \
      #      ../llvm

      #- name: Build LLVM
      #  run: |
      #    cd llvm-project/build
      #    ninja
      #  env:
      #    LLVM_PARALLEL_COMPILE_JOBS: ${{ matrix.arch == 'x86' && 8 || 8 }}

      - name: Display build information
        run: |
          echo "Architecture: ${{ matrix.arch }}"
          echo "Build completed on $(date)"

      #- name: Pull request
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  run: |
      #    pwd
      #    cd llvm-project
      #    pwd
      #    git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/ampere-solution/llvm-project.git
      #    git pull origin main --rebase 
             
      - name: Commit changes
        env: 
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: tinguyen-ampere
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          pwd
          cd llvm-project
          ls -la
          pwd
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "tinguyen@amperecomputing.com"
          echo 'Testing... ' >> README.md
          git add ./README.md
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
      
############### Push action section ##################################################
      #- name: Push changes
      #  env: 
      #     PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      #  run: |
      #     cd llvm-project
      #     git push https://${PAT_TOKEN}@github.com/ampere-solution/llvm-project.git HEAD:main
      #     shell: bash

          
      - name: Push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: tinguyen-ampere
        run: |
          pwd
          cd llvm-project
          pwd
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "tinguyen@amperecomputing.com"
          git pull --rebase origin main
          git branch -M main
          git push https://${PAT_TOKEN}@github.com/ampere-solution/llvm-project.git HEAD:main


          
      # - name: Push command 
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.PAT_TOKEN }}

      #    git push https://${PAT_TOKEN}@github.com/ampere-solution/llvm-project.git HEAD:main
      #    git push -u origin main
      #    git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/ampere-solution/llvm-project.git
      #    git branch -M main
      #    git push origin HEAD:main
          
      #- name: Push changes
      #  uses: ad-m/github-push-action@master
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    branch: ${{ github.ref }}
          
      #- name: Push changes
      #  uses: ampere-solution/llvm-project@main
      #  with:
      #    github_token: ${{ secrets.TAP_TOKEN }}

################ Continuous Deployment/Delivery ###########################################
  deploy:
    needs: LLVM_build
    strategy:
      matrix:
        arch: [arm64]
    runs-on: arc-runner-set-ampere

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ampere-solution/llvm-project
          path: llvm-project

      - name: List repository contents
        run: |
          pwd
          ls -la $GITHUB_WORKSPACE
      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build python3

      - name: Configure LLVM build
        run: |
          mkdir -p llvm-project/build
          cd llvm-project/build
          cmake -G Ninja \
            -DLLVM_ENABLE_PROJECTS="clang" \
             -DLLVM_ENABLE_RUNTIMES="libunwind;libcxx;libcxxabi" \
            -DLLVM_TARGETS_TO_BUILD="AArch64;X86" \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            ../llvm

      - name: Build LLVM
        run: |
          pwd
          cd llvm-project/build
          ninja
        env:
          LLVM_PARALLEL_COMPILE_JOBS: ${{ matrix.arch == 'x86' && 8 || 8 }}
          
      - name: install LLVM
        run: |
          pwd
          ls -la
          cd llvm-project/build
          sudo ninja install
        env:
          LLVM_PARALLEL_COMPILE_JOBS: ${{ matrix.arch == 'x86' && 8 || 8 }}

      - name: Verify the installation
        run: |
          clang --version
          llvm-config --version
          
